// <auto-generated />
using Ecommerce.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Fruits",
                            Description = "Fresh organic bananas, rich in potassium. Perfect for smoothies or snacking.",
                            ImageUrl = "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400",
                            Name = "Organic Bananas",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Fruits",
                            Description = "Crisp and sweet red apples. Great for eating fresh or baking.",
                            ImageUrl = "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400",
                            Name = "Red Apples",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Fruits",
                            Description = "Juicy oranges packed with Vitamin C. Perfect for fresh juice.",
                            ImageUrl = "https://images.unsplash.com/photo-1547514701-42782101795e?w=400",
                            Name = "Fresh Oranges",
                            Price = 5.4900000000000002
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Vegetables",
                            Description = "Fresh vine-ripened tomatoes. Essential for salads and cooking.",
                            ImageUrl = "https://images.unsplash.com/photo-1546470427-227e365ecca3?w=400",
                            Name = "Tomatoes",
                            Price = 3.4900000000000002
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Vegetables",
                            Description = "Russet potatoes, perfect for baking, mashing, or frying.",
                            ImageUrl = "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
                            Name = "Potatoes",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Vegetables",
                            Description = "Crunchy orange carrots, great for snacking or cooking.",
                            ImageUrl = "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
                            Name = "Fresh Carrots",
                            Price = 2.4900000000000002
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "Vegetables",
                            Description = "Fresh broccoli florets, packed with nutrients and fiber.",
                            ImageUrl = "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400",
                            Name = "Broccoli",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "Dairy",
                            Description = "Fresh whole milk, rich and creamy. Perfect for drinking or cooking.",
                            ImageUrl = "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
                            Name = "Whole Milk (1 Gallon)",
                            Price = 4.79
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "Dairy",
                            Description = "Sharp cheddar cheese, aged for bold flavor. Great for sandwiches.",
                            ImageUrl = "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400",
                            Name = "Cheddar Cheese",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryName = "Dairy",
                            Description = "Protein-rich Greek yogurt. Perfect for breakfast or smoothies.",
                            ImageUrl = "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
                            Name = "Greek Yogurt",
                            Price = 5.4900000000000002
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryName = "Pantry",
                            Description = "Healthy whole grain brown rice. Perfect side dish or base.",
                            ImageUrl = "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
                            Name = "Brown Rice (2lb)",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryName = "Pantry",
                            Description = "Freshly baked whole wheat bread. Perfect for sandwiches.",
                            ImageUrl = "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
                            Name = "Whole Wheat Bread",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryName = "Pantry",
                            Description = "Italian pasta, perfect for any sauce. Quick and easy meal.",
                            ImageUrl = "https://images.unsplash.com/photo-1551462147-37463d4ba10c?w=400",
                            Name = "Pasta (1lb)",
                            Price = 2.4900000000000002
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryName = "Snacks",
                            Description = "Crispy salted potato chips. Perfect snack for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400",
                            Name = "Potato Chips",
                            Price = 4.4900000000000002
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryName = "Snacks",
                            Description = "Delicious homestyle chocolate chip cookies. Sweet treat!",
                            ImageUrl = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400",
                            Name = "Chocolate Chip Cookies",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryName = "Snacks",
                            Description = "Premium mixed nuts with almonds, cashews, and pecans.",
                            ImageUrl = "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400",
                            Name = "Mixed Nuts",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryName = "Beverages",
                            Description = "Fresh-squeezed orange juice, no added sugar. Pure citrus goodness.",
                            ImageUrl = "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400",
                            Name = "Orange Juice (64oz)",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryName = "Beverages",
                            Description = "Pure spring water, 12-pack of 16.9oz bottles. Stay hydrated!",
                            ImageUrl = "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400",
                            Name = "Bottled Water (12 pack)",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryName = "Beverages",
                            Description = "Premium green tea bags. Rich in antioxidants and flavor.",
                            ImageUrl = "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
                            Name = "Green Tea",
                            Price = 6.4900000000000002
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryName = "Beverages",
                            Description = "Premium arabica coffee beans. Rich, smooth, and aromatic.",
                            ImageUrl = "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
                            Name = "Coffee Beans (1lb)",
                            Price = 12.99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
